import { Builder } from '../../../engine/Builder';

// https://github.com/CoderDE/FicsIt-Networks/blob/8df216ff8f8f8326c7a7f280c72d15106aa51c78/Source/FicsItNetworks/FicsItKernel/Processor/Lua/LuaProcessorStateStorage.cpp
export function transformFINLuaProcessorStateStorage(builder: Builder): void {
  builder
    .int('a')
    .str('b')
    .str('c')
    .int('d')
    .str('e')
    .str('f')
    .int('g')
    .str('h')
    .str('i')
    .int('j_0')
    .int('j_1')
    .int('j_2')
    .str('k_0')
    .int('k_1')
    .str('k_2')
    .str('k_3')
    .int('l')
    .str('m_0')
    .str('m_1')
    .int('n')
    .str('o_0')
    .str('o_1')
    .int('p_0')
    .int('p_1')
    .int('p_2')
    .str('q')
    .int('qk_1')
    .str('qk_2')
    .str('qk_3')
    .int('ql')
    .str('qm_0')
    .str('qm_1')
    .int('qn')
    .str('qo_0')
    .str('qo_1')
    .int('qp_0')
    .int('qp_1')
    .int('r_0')
    .str('r_1')
    .int('r_2')
    .int('r_3')
    .str('r_4base64') // globals
    .str('r_5base64') // thread
    .int('s')
    .str('s_0')
    .int('s_1')
    .int('s_2')
    .str('s_2_0')
    .int('s_2_1')
    .int('s_2_2')
    .str('s_3_0')
    .int('s_3_1')
    .int('s_3_2')
    .str('s_4_0')
    .int('s_4_1')
    .int('s_4_2')
    .str('s_5_0')
    .int('s_5_1')
    .int('s_5_2')
    .str('s_6_0')
    .int('s_6_1')
    .int('s_6_2')
    .str('s_7_0')
    .int('s_7_1')
    .int('s_7_2')
    .str('s_8_0')
    .int('s_8_1')
    .int('s_8_2')
    .str('s_9_0')
    .int('s_9_1')
    .int('s_9_2')
    .str('s_A_0')
    .int('s_A_1')
    .int('s_A_2')

    .hex('_tmp', 256)
    .debugger();
}
